// this object contains redux action types

export const fruitsConstants = {
  REQUEST_FRUITS: "REQUEST_FRUITS",
  REQUEST_SUCCESS: "REQUEST_SUCCESS",
  REQUEST_FAILURE: "REQUEST_FAILURE",

  ADD_FRUIT: "ADD_FRUIT",
  ADD_SUCCESS: "ADD_SUCCESS",
  ADD_FAILURE: "ADD_FAILURE",

  DELETE_FRUIT: "DELETED_FRUIT",
  DELETE_SUCCESS: "DELETE_SUCCESS",
  DELETE_FAILURE: "DELETE_FAILURE",

  UPDATE_FRUIT: "UPDATE_FRUIT",
  UPDATE_SUCCESS: "UPDATE_SUCCESS",
  UPDATE_FAILURE: "UPDATE_FAILURE",

  TOGGLE_EDIT: "TOGGLE_EDIT"
};
